version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lledo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lledo
      POSTGRES_PASSWORD: lledo_secret_2024
      POSTGRES_DB: lledo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
